mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.blog.myblog.dao
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
    url: jdbc:mysql://192.168.131.154:3306/blog_database?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
=======
    url: jdbc:mysql://192.168.131.153:3306/blog_database?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
>>>>>>> b474ed02152f141f47166ab30c1624b8a96800c1
    username: root
    password: Aa123456